"Glamour"
Gofer new
	squeaksource: 'CollectionExtensions';
	package: 'CollectionExtensions';
	load.
Gofer new
	squeaksource: 'HealthReportProducer';
	package: 'HealthReportProducer';
	load.
Gofer new
	squeaksource: 'Mondrian'; 
	package: 'Mondrian';
	package: 'MondrianPaintings';
	load.
Gofer new
    squeaksource: 'Glamour';
    package: 'Glamour-Announcements';
    package: 'Glamour-Browsers';
    package: 'Glamour-Core';
    package: 'Glamour-Examples';
    package: 'Glamour-Helpers';
    package: 'Glamour-Morphic';
    package: 'Glamour-Presentations';
    package: 'Glamour-Reporter';
    package: 'Glamour-Scripting';
    package: 'Glamour-Tests';
    package: 'Glamour-Tools';
    load.
!
Gofer new
    renggli: 'petit';
    package: 'PetitGui';
	load
