"Glamour"
Gofer new
	squeaksource: 'Glamour';
	package: 'Glamour-Announcements';
	package: 'Glamour-Browsers';
	package: 'Glamour-Core';
	package: 'Glamour-Helpers';
	package: 'Glamour-Morphic-Renderer';
	package: 'Glamour-Morphic-Theme';
	package: 'Glamour-Morphic-Widgets';
	package: 'Glamour-Presentations';
	package: 'Glamour-Tools';
	load.
!
"PetitParser"
Gofer new
	renggli: 'petit';
	package: 'PetitGui';
	load.
!
PPBrowser open
