"Glamour"
Gofer new
	squeaksource: 'Glamour';
	version: 'Glamour-Announcements-TudorGirba.6';
	version: 'Glamour-Browsers-TudorGirba.90';
	version: 'Glamour-Core-TudorGirba.221';
	version: 'Glamour-Helpers-TudorGirba.32';
	version: 'Glamour-Morphic-Renderer-TudorGirba.139';
	version: 'Glamour-Morphic-Theme-TudorGirba.55';
	version: 'Glamour-Morphic-Widgets-TudorGirba.31';
	version: 'Glamour-Presentations-TudorGirba.109';
	version: 'Glamour-Tools-TudorGirba.50';
	load.
!
"PetitParser"
Gofer new
	renggli: 'petit';
	package: 'PetitGui';
	load.
!
PPBrowser open.