"Pier 2"
Gofer new
	renggli: 'pier2';
	package: 'Pier-Core';
	package: 'Pier-Pharo-Core';
	package: 'Pier-Model';
	package: 'Pier-Pharo-Model';
	package: 'Pier-Tests-Model';
	package: 'Pier-Seaside';
	package: 'Pier-Pharo-Seaside';
	package: 'Pier-Security';
	package: 'Pier-Pharo-Persistency';
	package: 'Pier-Tests-Security';
	load.
Gofer new
    renggli: 'pier2';
	package: 'Pier-Setup';
	package: 'Pier-Blog';
	package: 'Pier-Book';
	package: 'Pier-Documents';
	package: 'Pier-EditorEnh';
	package: 'Pier-LinkChecker';
	package: 'Pier-Google';
	package: 'Pier-TagCloud';
	package: 'Pier-Twitter';
	load.
