"Basic"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Grease-Core';
	package: 'Grease-Pharo-Core';
	package: 'Grease-Tests-Core';
	package: 'Grease-Tests-Pharo-Core';
	package: 'Seaside-Core';
	package: 'Seaside-Pharo-Core';
	package: 'Seaside-Tests-Core';
	package: 'Seaside-Tests-UTF8';
	package: 'Seaside-Tests-Pharo-Core';
	package: 'Seaside-Canvas';
	package: 'Seaside-Pharo-Canvas';
	package: 'Seaside-Tests-Canvas';
	package: 'Seaside-Session';
	package: 'Seaside-Tests-Session';
	package: 'Seaside-Component';
	package: 'Seaside-Tests-Component';
	package: 'Seaside-RenderLoop';
	package: 'Seaside-Tests-RenderLoop';
	package: 'Seaside-Tools-Core';
	package: 'Seaside-Widgets';
	package: 'Seaside-Environment';
	package: 'Seaside-Pharo-Environment';
	package: 'Seaside-Tests-Environment';
	load.
!
"Traditional"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Tests-Functional';
	package: 'Seaside-Tests-Pharo-Functional';
	package: 'Seaside-Pharo-Continuation';
	package: 'Seaside-Tests-Pharo-Continuation';
	package: 'Seaside-Flow';
	package: 'Seaside-Pharo-Flow';
	package: 'Seaside-Tests-Flow';
	package: 'Seaside-Tools-Web';
	package: 'Seaside-Pharo-Tools-Web';
	package: 'Seaside-Tests-Tools-Web';
	package: 'Seaside-Development';
	package: 'Seaside-Pharo-Development';
	package: 'Seaside-Tests-Development';
	package: 'Seaside-Tests-Pharo-Development';
	package: 'Seaside-Examples';
	package: 'Seaside-Tests-Examples';
	load.
!
"Development and Admin Tools"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Grease-Slime';
	package: 'Grease-Tests-Slime';
	package: 'Seaside-Slime';
	package: 'Seaside-Tests-Slime';
	package: 'Seaside-Tools-OmniBrowser';
	package: 'Seaside-Pharo-Tools-OmniBrowser';
	load.
!
"RSS"
Gofer new
	squeaksource: 'Seaside30';
	package: 'RSS-Core';
	package: 'RSS-Tests-Core';
	package: 'RSS-Examples';
	load.
!
"Javascript"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Javascript-Core';
	package: 'Javascript-Pharo-Core';
	package: 'Javascript-Tests-Core';
	package: 'Javascript-Tests-Pharo-Core';
	package: 'JQuery-Core';
	package: 'JQuery-Tests-Core';
	package: 'JQuery-UI';
	package: 'JQuery-Tests-UI';
	package: 'Prototype-Core';
	package: 'Prototype-Tests-Core';
	package: 'Scriptaculous-Core';
	package: 'Scriptaculous-Tests-Core';
	package: 'Scriptaculous-Components';
	package: 'Scriptaculous-Tests-Components';
	package: 'Comet-Core';
	package: 'Comet-Examples';
	package: 'Comet-Pharo-Core';
	package: 'Comet-Tests-Core';
	load.
!
"Other Packages"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Welcome';
	package: 'Seaside-Tests-Welcome';
	package: 'Seaside-HTML5';
	package: 'Seaside-Tests-HTML5';
	package: 'Seaside-InternetExplorer';
	package: 'Seaside-Tests-InternetExplorer';
	package: 'Seaside-Email';
	package: 'Seaside-Tests-Email';
	package: 'Seaside-Pharo-Email';
	load.
